spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

remove-bg-api:
  api-url: https://api.remove.bg/v1.0/removebg
  x-api-key: ${X-API-KEY}
#  My test key -> Ued1bRPtMjdLVtg3sfHntNUv, approx. 10 calls left

server:
  servlet:
    context-path: /api
  tomcat:
    max-http-form-post-size: 5MB

logging:
  file:
    name: ../../finbylog.log
  logback:
    rollingpolicy:
      total-size-cap: 100MB